/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsWorkspacesRouteImport } from './routes/settings.workspaces'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsSkillsRouteImport } from './routes/settings.skills'
import { Route as SettingsSecretsRouteImport } from './routes/settings.secrets'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsLoopsRouteImport } from './routes/settings.loops'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsBetaRouteImport } from './routes/settings.beta'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as ConnectCallbackRouteImport } from './routes/connect_.callback'
import { Route as SettingsWorkspacesWorkspaceIdRouteImport } from './routes/settings.workspaces_.$workspaceId'
import { Route as SettingsUsersLoginRouteImport } from './routes/settings.users_.$login'
import { Route as SettingsSkillsPluginIdRouteImport } from './routes/settings.skills_.$pluginId'
import { Route as SettingsLoopsLoopIdRouteImport } from './routes/settings.loops_.$loopId'
import { Route as SettingsIntegrationsConnectionIdRouteImport } from './routes/settings.integrations_.$connectionId'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsWorkspacesRoute = SettingsWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecretsRoute = SettingsSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLoopsRoute = SettingsLoopsRouteImport.update({
  id: '/loops',
  path: '/loops',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBetaRoute = SettingsBetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const ConnectCallbackRoute = ConnectCallbackRouteImport.update({
  id: '/connect_/callback',
  path: '/connect/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWorkspacesWorkspaceIdRoute =
  SettingsWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces_/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsUsersLoginRoute = SettingsUsersLoginRouteImport.update({
  id: '/users_/$login',
  path: '/users/$login',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSkillsPluginIdRoute = SettingsSkillsPluginIdRouteImport.update({
  id: '/skills_/$pluginId',
  path: '/skills/$pluginId',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLoopsLoopIdRoute = SettingsLoopsLoopIdRouteImport.update({
  id: '/loops_/$loopId',
  path: '/loops/$loopId',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsConnectionIdRoute =
  SettingsIntegrationsConnectionIdRouteImport.update({
    id: '/integrations_/$connectionId',
    path: '/integrations/$connectionId',
    getParentRoute: () => SettingsRoute,
  } as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/connect/callback': typeof ConnectCallbackRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/beta': typeof SettingsBetaRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/loops': typeof SettingsLoopsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/secrets': typeof SettingsSecretsRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/integrations/$connectionId': typeof SettingsIntegrationsConnectionIdRoute
  '/settings/loops/$loopId': typeof SettingsLoopsLoopIdRoute
  '/settings/skills/$pluginId': typeof SettingsSkillsPluginIdRoute
  '/settings/users/$login': typeof SettingsUsersLoginRoute
  '/settings/workspaces/$workspaceId': typeof SettingsWorkspacesWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/connect/callback': typeof ConnectCallbackRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/beta': typeof SettingsBetaRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/loops': typeof SettingsLoopsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/secrets': typeof SettingsSecretsRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/integrations/$connectionId': typeof SettingsIntegrationsConnectionIdRoute
  '/settings/loops/$loopId': typeof SettingsLoopsLoopIdRoute
  '/settings/skills/$pluginId': typeof SettingsSkillsPluginIdRoute
  '/settings/users/$login': typeof SettingsUsersLoginRoute
  '/settings/workspaces/$workspaceId': typeof SettingsWorkspacesWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/connect_/callback': typeof ConnectCallbackRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/beta': typeof SettingsBetaRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/loops': typeof SettingsLoopsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/secrets': typeof SettingsSecretsRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/integrations_/$connectionId': typeof SettingsIntegrationsConnectionIdRoute
  '/settings/loops_/$loopId': typeof SettingsLoopsLoopIdRoute
  '/settings/skills_/$pluginId': typeof SettingsSkillsPluginIdRoute
  '/settings/users_/$login': typeof SettingsUsersLoginRoute
  '/settings/workspaces_/$workspaceId': typeof SettingsWorkspacesWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/login'
    | '/pair'
    | '/settings'
    | '/connect/callback'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/beta'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/loops'
    | '/settings/providers'
    | '/settings/secrets'
    | '/settings/skills'
    | '/settings/source-control'
    | '/settings/users'
    | '/settings/workspaces'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/settings/integrations/$connectionId'
    | '/settings/loops/$loopId'
    | '/settings/skills/$pluginId'
    | '/settings/users/$login'
    | '/settings/workspaces/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connect'
    | '/login'
    | '/pair'
    | '/settings'
    | '/connect/callback'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/beta'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/loops'
    | '/settings/providers'
    | '/settings/secrets'
    | '/settings/skills'
    | '/settings/source-control'
    | '/settings/users'
    | '/settings/workspaces'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/settings/integrations/$connectionId'
    | '/settings/loops/$loopId'
    | '/settings/skills/$pluginId'
    | '/settings/users/$login'
    | '/settings/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/_chat'
    | '/connect'
    | '/login'
    | '/pair'
    | '/settings'
    | '/connect_/callback'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/beta'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/loops'
    | '/settings/providers'
    | '/settings/secrets'
    | '/settings/skills'
    | '/settings/source-control'
    | '/settings/users'
    | '/settings/workspaces'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/settings/integrations_/$connectionId'
    | '/settings/loops_/$loopId'
    | '/settings/skills_/$pluginId'
    | '/settings/users_/$login'
    | '/settings/workspaces_/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  LoginRoute: typeof LoginRoute
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ConnectCallbackRoute: typeof ConnectCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/workspaces': {
      id: '/settings/workspaces'
      path: '/workspaces'
      fullPath: '/settings/workspaces'
      preLoaderRoute: typeof SettingsWorkspacesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/secrets': {
      id: '/settings/secrets'
      path: '/secrets'
      fullPath: '/settings/secrets'
      preLoaderRoute: typeof SettingsSecretsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/loops': {
      id: '/settings/loops'
      path: '/loops'
      fullPath: '/settings/loops'
      preLoaderRoute: typeof SettingsLoopsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/beta': {
      id: '/settings/beta'
      path: '/beta'
      fullPath: '/settings/beta'
      preLoaderRoute: typeof SettingsBetaRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/connect_/callback': {
      id: '/connect_/callback'
      path: '/connect/callback'
      fullPath: '/connect/callback'
      preLoaderRoute: typeof ConnectCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/workspaces_/$workspaceId': {
      id: '/settings/workspaces_/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/settings/workspaces/$workspaceId'
      preLoaderRoute: typeof SettingsWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users_/$login': {
      id: '/settings/users_/$login'
      path: '/users/$login'
      fullPath: '/settings/users/$login'
      preLoaderRoute: typeof SettingsUsersLoginRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/skills_/$pluginId': {
      id: '/settings/skills_/$pluginId'
      path: '/skills/$pluginId'
      fullPath: '/settings/skills/$pluginId'
      preLoaderRoute: typeof SettingsSkillsPluginIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/loops_/$loopId': {
      id: '/settings/loops_/$loopId'
      path: '/loops/$loopId'
      fullPath: '/settings/loops/$loopId'
      preLoaderRoute: typeof SettingsLoopsLoopIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations_/$connectionId': {
      id: '/settings/integrations_/$connectionId'
      path: '/integrations/$connectionId'
      fullPath: '/settings/integrations/$connectionId'
      preLoaderRoute: typeof SettingsIntegrationsConnectionIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsBetaRoute: typeof SettingsBetaRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsLoopsRoute: typeof SettingsLoopsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSecretsRoute: typeof SettingsSecretsRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsWorkspacesRoute: typeof SettingsWorkspacesRoute
  SettingsIntegrationsConnectionIdRoute: typeof SettingsIntegrationsConnectionIdRoute
  SettingsLoopsLoopIdRoute: typeof SettingsLoopsLoopIdRoute
  SettingsSkillsPluginIdRoute: typeof SettingsSkillsPluginIdRoute
  SettingsUsersLoginRoute: typeof SettingsUsersLoginRoute
  SettingsWorkspacesWorkspaceIdRoute: typeof SettingsWorkspacesWorkspaceIdRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsBetaRoute: SettingsBetaRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsLoopsRoute: SettingsLoopsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSecretsRoute: SettingsSecretsRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsWorkspacesRoute: SettingsWorkspacesRoute,
  SettingsIntegrationsConnectionIdRoute: SettingsIntegrationsConnectionIdRoute,
  SettingsLoopsLoopIdRoute: SettingsLoopsLoopIdRoute,
  SettingsSkillsPluginIdRoute: SettingsSkillsPluginIdRoute,
  SettingsUsersLoginRoute: SettingsUsersLoginRoute,
  SettingsWorkspacesWorkspaceIdRoute: SettingsWorkspacesWorkspaceIdRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  ConnectRoute: ConnectRoute,
  LoginRoute: LoginRoute,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ConnectCallbackRoute: ConnectCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
